// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIKY3nl9kop7MCDOZPDhAVoqWBQgCVebQ',
    appId: '1:837911345472:web:841ff729a8d67c28c0e2a5',
    messagingSenderId: '837911345472',
    projectId: 'quizify-27c62',
    authDomain: 'quizify-27c62.firebaseapp.com',
    storageBucket: 'quizify-27c62.firebasestorage.app',
    measurementId: 'G-CM17LZ6R5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_g4bw94kgrMQXhJRoCwCaHSmu4jLg4DQ',
    appId: '1:837911345472:android:5047178d574552c2c0e2a5',
    messagingSenderId: '837911345472',
    projectId: 'quizify-27c62',
    storageBucket: 'quizify-27c62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Qi7awfNQ3GElGDDNvJJlrEqCI58A1o4',
    appId: '1:837911345472:ios:2d14660bfc5ece5cc0e2a5',
    messagingSenderId: '837911345472',
    projectId: 'quizify-27c62',
    storageBucket: 'quizify-27c62.firebasestorage.app',
    iosBundleId: 'com.example.quizify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Qi7awfNQ3GElGDDNvJJlrEqCI58A1o4',
    appId: '1:837911345472:ios:2d14660bfc5ece5cc0e2a5',
    messagingSenderId: '837911345472',
    projectId: 'quizify-27c62',
    storageBucket: 'quizify-27c62.firebasestorage.app',
    iosBundleId: 'com.example.quizify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIKY3nl9kop7MCDOZPDhAVoqWBQgCVebQ',
    appId: '1:837911345472:web:e1928b4bbfb1a7c7c0e2a5',
    messagingSenderId: '837911345472',
    projectId: 'quizify-27c62',
    authDomain: 'quizify-27c62.firebaseapp.com',
    storageBucket: 'quizify-27c62.firebasestorage.app',
    measurementId: 'G-2MF6EMZXGH',
  );
}
